version: "3"
 
services:
  jenkins:
    user: root
    image: "jenkins_gary:latest"
    ports:
      - "8080:8080"s
    volumes:
      - ./jenkins_home:/var/jenkins_home

    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge
